spring:
 jpa:
  hibernate:
   ddl-auto: update
 datasource:
  url: jdbc:mysql://localhost/fornecedor?createDatabaseIfNotExist=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  username: rootprod
  password: 1234
